runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /fonts
  static_dir: node_modules/bootstrap/dist/fonts 

- url: /node_modules
  static_dir: node_modules

- url: /app 
  static_dir: app 

- url: /font-awesome
  static_dir: static/font-awesome 

- url: /bootstrap-social
  static_dir: node_modules/bootstrap-social
  
- url: /systemjs.config
  static_files: systemjs.config.js
  upload: systemjs\.config\.js
  secure: always

- url: /jquery
  static_files: node_modules/jquery/dist/jquery.min.js
  upload: node_modules/jquery/dist/jquery\.min\.js
  secure: always

- url: /bootstrap-css
  static_files: node_modules/bootstrap/dist/css/bootstrap.min.css
  upload: node_modules/bootstrap/dist/css/bootstrap\.min\.css
  secure: always

- url: /bootstrap-js
  static_files: node_modules/bootstrap/dist/js/bootstrap.min.js
  upload: node_modules/bootstrap/dist/js/bootstrap\.min\.js
  secure: always

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
