application: customrejection
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /partials
  static_dir: static/partials

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

- url: /_ah/spi/.*
  script: endpoints_backend.api
  secure: always

libraries:
- name: endpoints
  version: latest
- name: pycrypto
  version: latest