runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /app 
  static_dir: app 

- url: /systemjs.config
  static_files: systemjs.config.js
  upload: systemjs\.config\.js
  secure: always

- url: /angular2
  static_dir: angular2

- url: /@angular 
  static_dir: angular2
  
- url: /rxjs
  static_dir: rxjs

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
